// properties.js
import Images from "./images";
const properties= [
  {
    id: 1,
    title: 'Luxurious Beachfront Villa',
    description: 'Stunning villa located right on the beach, offering breathtaking ocean views.',
    price: 500,
    location: 'Goa, India',
    bedrooms: 2,
    amenities: ['WiFi', 'Air Conditioning', 'Infinity Pool', 'Hot Tub', 'Free Parking', 'Pet Friendly', 'Breakfast Included', 'Gym', 'Sauna', 'Private Chef'],
    images: [Images[0]],
    rating: '4.5/5 (500)',
  },
  {
    id: 2,
    title: 'Cozy Mountain Cabin',
    description: 'A cozy cabin in the mountains with a beautiful view and peaceful surroundings.',
    price: 300,
    location: 'Manali, India',
    bedrooms: 3,
    amenities: ['WiFi', 'Fireplace', 'Free Parking', 'Pet Friendly', 'Breakfast Included', 'Hot Tub', 'Washer/Dryer', 'Kitchen', 'BBQ Grill', 'Game Room'],
    images: [Images[1]],
    rating: '4.7/5 (300)',
  },
  {
    id: 3,
    title: 'Modern City Loft',
    description: 'A stylish loft in the city center with modern amenities and a great view.',
    price: 600,
    location: 'New Delhi, India',
    bedrooms: 2,
    amenities: ['WiFi', 'Air Conditioning', 'Free Parking', 'Gym', 'Pet Friendly', 'Breakfast Included', 'Washer/Dryer', 'Kitchen', 'Cable TV', 'Rooftop Access'],
    images: [Images[3]],
    rating: '4.8/5 (450)',
  },
  {
    id: 4,
    title: 'Spacious Suburban House',
    description: 'A large house in the suburbs, perfect for families and groups.',
    price: 400,
    location: 'Bangalore, India',
    bedrooms: 4,
    amenities: ['WiFi', 'Air Conditioning', 'Free Parking', 'Pet Friendly', 'Breakfast Included', 'Washer/Dryer', 'Kitchen', 'BBQ Grill', 'Game Room', 'Private Yard'],
    images: [Images[4]],
    rating: '4.6/5 (400)',
  },
  {
    id: 5,
    title: 'Charming Countryside Cottage',
    description: 'A quaint cottage in the countryside, ideal for a quiet getaway.',
    price: 250,
    location: 'Ooty, India',
    bedrooms: 2,
    amenities: ['WiFi', 'Free Parking', 'Pet Friendly', 'Breakfast Included', 'Fireplace', 'Washer/Dryer', 'Kitchen', 'BBQ Grill', 'Game Room', 'Private Yard'],
    images: [Images[5]],
    rating: '4.5/5 (350)',
  },
  {
    id: 6,
    title: 'Luxury Penthouse Suite',
    description: 'An exclusive penthouse suite with panoramic city views and premium amenities.',
    price: 1200,
    location: 'Mumbai, India',
    bedrooms: 3,
    amenities: ['WiFi', 'Air Conditioning', 'Infinity Pool', 'Hot Tub', 'Free Parking', 'Gym', 'Sauna', 'Private Chef', 'Breakfast Included', 'Rooftop Access'],
    images: [Images[6]],
    rating: '4.9/5 (200)',
  },
  {
    id: 7,
    title: 'Secluded Forest Retreat',
    description: 'A peaceful retreat in the forest, perfect for nature lovers.',
    price: 350,
    location: 'Coorg, India',
    bedrooms: 2,
    amenities: ['WiFi', 'Free Parking', 'Pet Friendly', 'Breakfast Included', 'Fireplace', 'Hot Tub', 'Washer/Dryer', 'Kitchen', 'BBQ Grill', 'Private Yard'],
    images: [Images[7]],
    rating: '4.7/5 (300)',
  },
  {
    id: 8,
    title: 'Beachfront Bungalow',
    description: 'A cozy bungalow right on the beach, offering stunning sea views.',
    price: 450,
    location: 'Goa, India',
    bedrooms: 2,
    amenities: ['WiFi', 'Air Conditioning', 'Free Parking', 'Pet Friendly', 'Breakfast Included', 'Washer/Dryer', 'Kitchen', 'BBQ Grill', 'Private Beach', 'Rooftop Access'],
    images: [Images[8]],
    rating: '4.6/5 (350)',
  },
  {
    id: 9,
    title: 'Modern City Apartment',
    description: 'A modern apartment in the heart of the city with all the necessary amenities.',
    price: 450,
    location: 'Mumbai, India',
    bedrooms: 1,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Gym', 'Free Parking', 'Pet Friendly', 'Washer/Dryer', 'Cable TV', 'Breakfast Included', 'Rooftop Access'],
    images: [Images[9]],
    rating: '4.6/5 (450)',
  },
  // ... Repeat similar objects for up to 50 entries ...
  {
    id: 50,
    title: 'Modern City Apartment',
    description: 'A modern apartment in the heart of the city with all the necessary amenities.',
    price: 450,
    location: 'Mumbai, India',
    bedrooms: 1,
    amenities: ['WiFi', 'Air Conditioning', 'Kitchen', 'Gym', 'Free Parking', 'Pet Friendly', 'Washer/Dryer', 'Cable TV', 'Breakfast Included', 'Rooftop Access'],
    images: [Images[10]],
    rating: '4.6/5 (450)',
  }
];

export default properties;
